### ISSUE TITLE
Body of post adding a closing tag and breaking window.isoData

### ISSUE THREAD

**Issue by threenplusone** [LemmyNet/lemmy-ui#1192]
### Issue Summary

If you post body contains something that looks like an unclosed HTML tag, it will be closed automatically and the **window.isoData** will break.

When this happens, you cannot use the profile dropdown (top-right of the page).

[Here is an example](https://aussie.zone/post/13723)

Impacts both the PC website and the Mobile website.

### Steps to Reproduce

1. Create a post containing **&lt;s&gt;**
2. View the community page or the post itself.
3. Try to dropdown your profile.

### Technical details

console is logging:
```
client.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'site_res')
    at client.js:2:2175012
    at client.js:2:2175483
    at client.js:2:2175487
```

**Comment by threenplusone** [comment]
It also prevents upvoting and downvoting on all posts on the page when this occurs.

**Comment by threenplusone** [comment]
Seems like this broke between **v0.17.3** and **0.17.4-rc.4**.

Here is a similar example:
[v0.17.3](https://thesimplecorner.org/post/4320) - Works fine
[0.17.4-rc.4](https://aussie.zone/post/13723) - Broken

**Comment by Nutomic** [comment]
Fixed in 0.17.4

**Comment by jimmyhiggs337** [comment]
I'm still having this issue when trying to set up my own instance on lemmy-ui  0.18.4

**Comment by zmiguel** [comment]
same issue here after upgrading to 0.19.3. no idea what to do
