### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by skossan** [LemmyNet/lemmy-ui#1300]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

The notification bell shows a 1 even though I have marked all notifications as read.

I've tried to clear cache and restart browser. I've also tried incognito browser. 

I tried to mark as un-read and mark as read again and it didn't work.

![image](https://github.com/LemmyNet/lemmy-ui/assets/31191132/881ed085-f5ad-40ba-9f9f-1fd4a84ed25f)

### Steps to Reproduce

No idea. 

This started to happen a couple days ago.

### Technical Details

No errors in the console.

### Version

I can't only see BE: 0.17.4. FE is not displayed anymore.

### Lemmy Instance URL

lemmy.world

**Comment by thingsiplay** [comment]
Same issue here, since months. Recently counter got up to 2 phantom unread messages. I have unblocked every user, but this didn't solve the issue either. My instance is beehaw.org. Is this an issue for you still?

**Comment by dessalines** [comment]
What happens when you click the mark all as read button? 

I'm also remembering a bug we fixed in the back-end, that stops replies from blocked users. You'll need to tell your instance to update if you want that bug to stop happening.

**Comment by thingsiplay** [comment]
For me there is no mark all as read button. I click the read icon for every single message I get manually. I also unblocked every user and still no change. The 2 is my new 0. At least on my instance (beehaw.org) I told them in a post. After weeks I looked up the issues here.

**Comment by dessalines** [comment]
lemmy-ui has a mark all as read button, and this is the repo for lemmy-ui. If its hidden for some reason, it means your server is either running a really old version, or you're using a different ui.

**Comment by Nutomic** [comment]
Seems resolved, otherwise contact your instance admin to check the database.
