### ISSUE TITLE
[Bug]: Auto-refresh makes it impossible to read the feed

### ISSUE THREAD

**Issue by Auxx** [LemmyNet/lemmy-ui#1357]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

Lemmy feed is auto-refreshing every time a new post is added. This makes it impossible to read the feed as the screen just keeps scrolling away. Also all opened images and post previews instantly close. Please disable this feature as it's getting ridiculously unusable the more people join Lemmy.

### Steps to Reproduce

1. Open any Lemmy instance in the browser
2. Start reading the feed
3. Everything auto-refreshes non stop

### Technical Details

No

### Version

0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by amitkulk123** [comment]
I agree, it's harder to read posts on the feed when it scrolls automatically whenever it refreshes. I'd prefer a manual button where you can click it to refresh.

**Comment by daviessm** [comment]
This will be solved in the next release as the "pushed" post feature using WebSockets has been removed.

**Comment by alectrocute** [comment]
Resolved in 0.18.

**Comment by NicotineLL** [comment]
This is not resolved for me, I keep getting my feed pushed by new posts.

**Comment by alectrocute** [comment]
<img width="1237" alt="Screenshot 2023-06-22 at 9 49 49 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/2632a038-436e-4168-92c7-a17cc1726254">

The instance you're using is running this version, which is behind 0.18. This is resolved in 0.18. Thanks for your time helping improve Lemmy-UI.
