### ISSUE TITLE
[Bug]: Wrong HTTP Status Code for Many Errors

### ISSUE THREAD

**Issue by XDjackieXD** [LemmyNet/lemmy-ui#1444]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

Many errors report HTTP status code 200 while delivering an error status in the body.
This severely breaks caching (and other things) and should never happen.
A page should always return the same error code in the headers as in the body.

### Steps to Reproduce

1. open a new tab in your browser
2. open the dev tools and go to the network tab
3. open a nonexistent community like https://lemmy.world/c/bla and look at the response in the dev tools

### Technical Details

Examples:
- visiting a nonexistant (or not yet cached) community:
  `404: couldnt_find_community`
- getting a timeout from the backend:
  `404: FetchError: invalid json response body at http://lemmy:8536/api/v3/site? reason: Unexpected token 'T', "Timeout oc"... is not valid JSON` (which should not even be a 404 but rather a 5xx error...)

The first one can be reproduced on any lemmy instance and the second one I got on lemmy.world

### Version

0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by cloventt** [comment]
Possibly related to #1335 . Seems like error pages in general would benefit from a tidy-up.

**Comment by SleeplessOne1917** [comment]
Fixed in #1024.

**Comment by XDjackieXD** [comment]
This does not fix this.
While the error page now looks nicer, it still returns HTTP code 200 for the 404 page (tested with 0.18.0).
