### ISSUE TITLE
Comment draft gets deleted when voting before submitting the comment

### ISSUE THREAD

**Issue by Schmork** [LemmyNet/lemmy-ui#1552]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When replying to another comment, a new input field opens.

**When voting on post or other comments, this input field closes** (this is the bug from my POV).

Re-opening the input field at the same location does not restore whatever you already typed.

The bug does not appear for top-level comments, since the input field in reply to the post is always there. For top-level comments, the input field does not close when the user votes. For all comment replies, the input field closes on voting activity, and the content is gone.

Not sure if it depends on my home instance, I only have one account. I can reproduce the bug on several other instances.

### Steps to Reproduce

1. Start writing a comment _in reply to any other comment_ (don't submit)
2. Vote on the post or any other comment
3. Your draft has disappeared. 

Re-opening the input field in reply to the same comment will open a blank field; what you already typed is lost.

### Technical Details

Desktop; Chrome 114.0.5735.134 @ Windows 10

### Lemmy Instance Version

BE: 0.18.0

### Lemmy Instance URL

https://lemmy.click/

**Comment by alectrocute** [comment]
Resolved in #1540. @SleeplessOne1917 could you confirm?

**Comment by Schmork** [comment]
Sorry @alectrocute, the bug is still present as described. Not resolved, nothing changed.

Additionally, I found that **voting also uncollapses all collapsed comment threads**. To reproduce:

1. collapse any comment or comment threads
2. vote on any comment
3. all comments and comment threads will uncollapse

Suspected underlying issue: It seems voting resets the UI, restoring text fields to their empty, hidden states and comment threads to their uncollapsed state.

**Comment by alectrocute** [comment]
The bug is present in 0.18 but has since been fixed. Please wait until next release to test again. Thanks!

**Comment by Schmork** [comment]
The bug is partially still there.

What's fixed: Collapsed comment threads stay collapsed when voting on other comments. Comment drafts are not deleted when voting on other comment chains.

But when I reply to a comment, and vote on a comment up or down on the same chain before submitting my reply, **the reply box closes and the content is gone.** Re-opening the box does not restore the draft.

#### Steps to Reproduce

1. Find a comment section with a comment chain.
2. Start replying to a comment (we call it comment X), don't submit.
3. Vote on a comment, which is a **(grand\*)parent or (grand\*)child** of X. (it can be a parent, or grandgrandgrandparent)
4. The reply to X is gone, draft is deleted.

Your open reply to X is unaffected, if you vote on another chain, or if you vote on a cousin or uncle of X.
