### ISSUE TITLE
Unable to login using Firefox mobile on iphone

### ISSUE THREAD

**Issue by efwis** [LemmyNet/lemmy-ui#1839]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Firefox mobile not allowing login on instances

### Steps to Reproduce

1. Tried to login on lemmy.ml with Firefox mobile on iPhone
2. tried to login on lemmy.zip with Firefox mobile on iPhone
3. hit login it tries to login but fails to do so

### Technical Details

iOS version 16.5.1

fils on firefox mobile version 114.4 (note: Firefox has not been updated for iPhone to 115 or 116)

no error messages or screenshots available

### Lemmy Instance Version

0.18.0

### Lemmy Instance URL

https://lemmy.zip and https//lemmy.ml

**Comment by lionirdeadman** [comment]
This issue can't really be resolved with this little information..

Please reopen if it is still happening and you can provide more information

**Comment by efwis** [comment]
It seems after putting in the information to login the login button stays inactive. What info would you need besides what I have mentioned? How would I go about getting some sort of log info

**Comment by lionirdeadman** [comment]
I'm not a developer, I just try to sort these issues.. I'm sorry, I don't know how to debug an iPhone browser :(

**Comment by moxvallix** [comment]
The issue is seemingly a bug in Firefox mobile, which, afaict, should be fixed in version 124.

Firefox mobile logs this error when form is submitted:
```
[Error] TypeError: undefined is not an object (evaluating 'this.fieldDetailsManager.activeHandler.onFormSubmitted')
	onSubmit (user-script:5:1:36221)
```

I tracked down this submit event to Firefox mobile's code: https://github.com/mozilla-mobile/firefox-ios/blob/240d2ce5a39dce12baed58f7133815be6276ae84/firefox-ios/Client/Assets/CC_Script/FormAutofillChild.ios.sys.mjs#L80

However, if we look at the latest version of the file (seemingly upcoming in 124 if commit messages are to be believed), we can see the function now has a guard clause that would assumedly fix this error: https://github.com/mozilla-mobile/firefox-ios/blob/059bade3dca31ab150b051811c7d5165be6d9a06/firefox-ios/Client/Assets/CC_Script/FormAutofillChild.ios.sys.mjs#L80

It might be possible to patch this somehow in Lemmy, but I think waiting for 124 will likely fix the issue.

---

For anyone curious how I debugged the iOS browser, I used: https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit

**Comment by Totogro** [comment]
I think I have the same issue on Brave Browser 1.66 (113) on iOS 16.7.7 on iPhone 8.
Once I managed to finally log in but I can't remember how...
My username and password are saved and automatically filled in the login form.

**Comment by moxvallix** [comment]
I tested again on Firefox mobile (126.2) and can now say that sign in works, seemingly fixed by the commit I linked earlier.

I think the issue @Totogro has is different, and might warrant a different issue.

**Comment by dessalines** [comment]
I just tried to login via firefox mobile on https://voyager.lemmy.ml , with android's AutoFill from my running KeepassDX, and it worked fine. 

I spose I could try from brave browser, but android's autofill should work the same.

**Comment by Totogro** [comment]
Still buggy for me :(

Funny : I tried to fill a new issue for this and... the button to submit is greyed out and doesn't work here on github !! 

Oh I just noticed something : when I want to view the password in the field (using the "eye" icon) the field empties itself... it may be a conflict between iOS saved password feature and the Brave Browser saved password feature. For some time now those two have created problems, and are not synced for some reason. So I can imagine that for some reason the browser shows the form as filled but the site thinks otherwise...

EDIT : I went into iOS password manager and there is an option Autofill. There the source for autofill was iOS Password Manager only, Brave Password Manager was not checked. So I checked it as well. (In fact only Brave knows my Lemmy password, iOS did not ask to save it) Now when the form is autofilled, I am asked the source, and if I choose Brave it works fine...

**Comment by dessalines** [comment]
Ohhh this is iOS. Ya I can't test that. 

> I went into iOS password manager and there is an option Autofill. There the source for autofill was iOS Password Manager only, Brave Password Manager was not checked. So I checked it as well. (In fact only Brave knows my Lemmy password, iOS did not ask to save it) Now when the form is autofilled, I am asked the source, and if I choose Brave it works fine...

Sounds like its fixed then, was just a misconfigured ios password manager issue?

**Comment by Totogro** [comment]
I wouldn't say it's fixed, the user experience is very bad, I know the way through all this, but others in my case wouldn't know (and probably would give up Lemmy altogether -- I almost did to be honest...)
I sent a message to the Brave about this issue. Maybe I should do the same to Apple.

Still, I wonder if there is nothing to do on Lemmy's side. What if the Connect button did not have that grey unusable state and would behave like any normal button, always clickable ? Maybe it would simply just work ?

**Comment by dessalines** [comment]
It shouldn't be always clickable, it needs to verify that those fields are filled in. This really needs to be opened up on iOS or brave's issue trackers.
