### ISSUE TITLE
When pictrs cant fetch site logo, entire site breaks

### ISSUE THREAD

**Issue by pallebone** [LemmyNet/lemmy-ui#2211]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Sometimes pictrs fails for many reasons, mostly because its not 100% perfect, to give a valid response to the logo call from lemmy-ui then the entire lemmy site no longer loads. This can be resolved by removing the site logo and uploading a new one again, without having to restart anything at all. Then lemmy-ui can get the logo again and the site functions normally once more. 

A better solution to the entire site breaking would be to display a broken image icon or something as the logo so that the site continues to operate when this happens. 

you can also remove the site logo directly from the postgres DB by using update site set icon = null where id = 1; and this also fixes the site again and then you can upload a new one.

Would make lemmy more reliable if this could be fixed, as pictrs cant be relied upon to be 100% reliable in every case every time until the end of the universe, as its just written by a normal human and so on. Bugs happen.

### Steps to Reproduce

1. Have site logo break.
2. Lemmy site no longer loads.

### Technical Details

Docker build with pictrs, same as 99% of lemmy servers.

### Lemmy Instance Version

0.18.5

### Lemmy Instance URL

https://lemmy.myserv.one/

**Comment by madeofstown** [comment]
Having the same issue on a fresh install of lemmy version 0.19.1 with pictrs version 0.4.7

**Comment by Illecors** [comment]
I've done a quick write up on how to circumvent it. Now that I think of it I should probably not have tagged it as "solved" as it's not a code change, but it honestly is solved from my perspective as a sysadmin.

https://lemmy.cafe/post/2346168

**Comment by db0** [comment]
A simpler workaround I followed is to remove the images/banner for a bit until pict-rs comes back.

First point them to some external image (here's I'm using the Haidra logo)

```sql
UPDATE site SET banner = 'https://aihorde.net/assets/img/logo.png' WHERE id = 1;
UPDATE site SET icon = 'https://aihorde.net/assets/img/logo.png' WHERE id = 1;
```

then restart your UI. Once it comes back, go to your settings and remove banner and icon

**Comment by madeofstown** [comment]
I can't believe this is still an issue. I thought for sure a huge increase in users would have spured more interest from the developer community. At this point I've moved on to new obsession but it appears maybe others have as well. Hopefully this finally gets fixed whenever 0.19.5 drops.

**Comment by SleeplessOne1917** [comment]
Working on this now. When this error occurs, do the lemmy-ui logs show an error like this?:

```
lemmy-ui-1  | Error: Input buffer contains unsupported image format
lemmy-ui-1  |     at Sharp.toBuffer (/app/node_modules/.pnpm/sharp@0.33.4/node_modules/sharp/lib/output.js:161:17)
lemmy-ui-1  |     at _callee$ (webpack://lemmy-ui/./src/server/utils/create-ssr-html.tsx?:79:20)
lemmy-ui-1  |     at tryCatch (/app/node_modules/.pnpm/@babel+runtime@7.24.8/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
lemmy-ui-1  |     at Generator.<anonymous> (/app/node_modules/.pnpm/@babel+runtime@7.24.8/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
lemmy-ui-1  |     at Generator.next (/app/node_modules/.pnpm/@babel+runtime@7.24.8/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
lemmy-ui-1  |     at asyncGeneratorStep (/app/node_modules/.pnpm/@babel+runtime@7.24.8/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
lemmy-ui-1  |     at _next (/app/node_modules/.pnpm/@babel+runtime@7.24.8/node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
lemmy-ui-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If so, I think I'm on the right track for reproducing the issue.

**Comment by dessalines** [comment]
Yep I believe it does. Or any sharp error.
