### ISSUE TITLE
Lemmy almost completely broken on iOS and MacOS devices 

### ISSUE THREAD

**Issue by victorrest** [LemmyNet/lemmy-ui#730]
Lemmy on iOS and MacOS devices is broken a lot of way. I think it's couse some JS error, but I'am not a developer.
E.g.: 
- Only could open a post after you click two times (!) on the link.
- Login is not work.
- Registration not work.
- Up/downvote not work.
- Top menu is not work.
- Logo/website name is unclickable, so you can't go back to the frontpage 
- etc.

I think nothing work on iOS and MacOS what is javascript-like on the website.

I checked from Safari browser and it show the follow errors:
- TypeError: undefined is not an object (evaulating 'this.ws.send') // error location is /static/js/client.js file.
- TypeError: null is non an object (evaulating '.$Li') // error location is /static/js/client.js file too.

However, this error is not affected every Lemmy site: so as I seen e.g. Lemmy.ml and Feddit.de is work fine on Apple devices, but mander.xyz, beehaw.org, lemmy.rollenspiel.monster, etc. is no.

I install Lemmy to my VPS too with Docker, and I have this JS problem on Apple devices too. Have you any idea what's the problem or how can I solve it. What couse is Lemmy.ml works fine while some others is no? Thanks for your help, I really like Lemmy and would like to solve this problem on my VPS too.

P.s.: I read in other github issue is somebody in Dev is not have Apple devices, in this cause I recommend this website: https://live.browserstack.com/dashboard
At here after a fast and free registration you can check any website from any devices, Apple devices too. I checked this problem from here too, I do not have MacOS too. 

I made some screenshots from the error, maybe help:
![](https://lemmy.ml/pictrs/image/984210c8-2d14-41cc-91c7-6f46ecc883fc.png)
![](https://lemmy.ml/pictrs/image/63cdb3ca-7526-42db-83dc-104fc33cbd37.png)

**Comment by dessalines** [comment]
These problems were fixed in the 0.16.6 release, make sure the server admins upgrade to that version of lemmy.

**Comment by victorrest** [comment]
Thanks for your fast reply. I will upgrade my Lemmy and try it. (I install 0.16.4 to my vps) But as I seen, e.g. https://mander.xyz/ is run the 0.16.6 version, and site is still crash iOS and MacOS too.

**Comment by dessalines** [comment]
Hrm... I can't see why some instances would block iOS javascript but others wouldn't if using the same code. Only thing I can think of is that the broken ones are using custom nginx's.

**Comment by victorrest** [comment]
Hmm, maybe. I will reinstall my VPS in the days, and install Lemmy new version with Docker from zero. After that I will feedback with the result.

**Comment by Nutomic** [comment]
Can you reproduce the problem on lemmy.ml?

**Comment by victorrest** [comment]
No, Lemmy.ml works fine on iOS and every MacOS version what I tested.

**Comment by Nutomic** [comment]
Then it sounds like a problem with the particular instances you mentioned. Contact the admins and ask them to fix it.

**Comment by GitOffMyBack** [comment]
> Then it sounds like a problem with the particular instances you mentioned. Contact the admins and ask them to fix it.

I've upgraded to 0.16.6 and I'm getting an "Unknown" error when attempting to log in on my iPhone using Firefox.

**Comment by dessalines** [comment]
I'm almost at the point where we should remove the CSP headers. They cause so many problems on iOS devices.

**Comment by Nutomic** [comment]
I disagree about removing CSP, because it can mitigate many security problems. The problem seems to be only with websocket, so it should be enough to change to `connect-src *`.

That said, our CSP is not really useful because it allows inline javascript, which we should really get rid of.

**Comment by sam365724** [comment]
@dessalines Is this fix in 0.16.6? I'm having problems with ios safari + chrome on ipad.

**Comment by dessalines** [comment]
@sam365724  I don't have an ios device so I can't test. https://lemmy.ml is running 0.16.6, could you test there?

**Comment by sam365724** [comment]
Sure, https://lemmy.ml/ works fine on Safari.
